### PR TITLE
Pull Request with a basic Deep RNN Model

### PR DESCRIPTION
**Pull request by stierney0505**
This model was developed through pair programming. It is our first iteration so any and all feedback is appreciated. It currently only takes in AAPL stock data and attempts to predict its closing price (the 5th column in the "data" dataFrame. In the future we will try to utilize a LSTM model, but we struggled to set that up.

### CODE REVIEW

**Review by zeshengchen — APPROVED** [review]
For future work, please try out other models, such as LSTM or transformer.

**Comment by zeshengchen** [comment]
Moreover, it is a good idea to upload Jupyter Notebook with outputs as well.

**Comment by zeshengchen** [comment]
> For future work, please try out other models, such as LSTM or transformer.

BTW, we will discuss about LSTM soon in the class.

**Comment by stierney0505** [comment]
> > For future work, please try out other models, such as LSTM or transformer.
> 
> BTW, we will discuss about LSTM soon in the class.

I was reading about RNN and LSTM's through the textbook prior to working on this, however, it was difficult to work with time series. We will continue to work on it and hopefully we will be able to use an LSTM or transformer before the midterm. 👍

**Review by HenrithicusGreenson — APPROVED** [review]

**Review by lukebushur — APPROVED** [review]
Looks good!

**Pull request merged**
