### PR TITLE
Server+basic model

### PR DESCRIPTION
**Pull request by stierney0505**
Created a basic web server in Flask. This provides both the frontend and backend separated into two python files, client_routes and serverExample_routes. 

# For Reviewers :
Reviewing the code for the models is unnecessary as the model code will be worked on tomorrow, Wednesday 03/05 as an entire group. The server and client code should be reviewed however.

### CODE REVIEW

**Comment by zeshengchen** [comment]
Please invite other group members to peer review this pull request when it is ready for reviews.

**Review by lukebushur — CHANGES_REQUESTED** [review]
Please fix the gitignore using \*\*/ (\*\*/\*.pyc for example) for ignoring these files in subdirectories

**Comment by stierney0505** [comment]
> Please fix the gitignore using **/ (**/*.pyc for example) for ignoring these files in subdirectories

I believe I have update the gitignore to address this

**Review by lukebushur — APPROVED** [review]
Looks good!

**Review by HenrithicusGreenson — APPROVED** [review]

**Pull request merged**
